export const homeData = [
  {
    id: 1,
    name: "mountain bike",
    rating: 4.8,
    time: "35 Min",
    desc: "El downhill es uno de los deportes más arriesgados que existen en el mundo y una de las modalidades del ciclismo de montaña que consiste en descender lo más rápido posible en una pista natural, que tiene obstáculos, que bien pueden ser naturales o también artificiales. El ganador es el que haga el menor tiempo posible en el descenso cronometrado.",
    starring: "Monika Riscanevo Jhon Machado",
    genres: "Deporte",
    tags: "Deporte Aventura",
    cover: "../img/images/deporte.jpeg",
    video: "../video/deporte.mp4",
    date: "06-Abril-2023",
  },
  {
    id: 2,
    name: "Fury",
    rating: 4.7,
    time: "2H : 10M",
    desc: "La historia está ambientada durante el último mes de la guerra en el teatro europeo durante la Segunda Guerra Mundial, en abril de 1945. Mientras los Aliados llevan a cabo su golpe final en Europa, un aguerrido sargento del ejército de Estados Unidos en la 2ª División Acorazada llamado Don Collier (Brad Pitt) comanda un tanque Sherman M4A3E8 llamado, y a su tripulación de cinco hombres en una mortal misión tras las líneas enemigas.",
    starring: "Bratt Pitt, Logan Lerman, Michael Peña",
    genres: "Action",
    tags: "Bélica Segunda Guerra",
    cover: "../img/images/fury.jpg",
    //cover: "../images/home1.jpg",
    video: "../video/video01.mp4",
    date: "10 Junio 2014",
  },
    {
      id: 3,
      name: "Futuro rey",
      rating: 4.8,
      time: "2H : 15M",
      desc: "La serie documental narra la vida en África de Jorge Alesanco, el primer hombre de la historia aceptado por una manada de leones salvajes, Este científico español, asentado en el corazón de Masai Mara, nos acerca a la vida salvaje de una manera única y fascinante, Mientras en el año 2020 el mundo vivía la peor pandemia en décadas, los animales salvajes de la sabana africana sufrieron una auténtica odisea, que nadie contó. Un equipo español de televisión, atrapado en Masai Mara durante el confinamiento, pudo narrar todo lo que allí ocurría ",
      starring: "Jorge Alesanco",
      genres: "Vida salvaje",
      tags: "Aventura, supervivencia",
      cover: "../img/images/upcome/futuroRey.png",
      video: "../video/serengueti.mp4",
      date: "13 Mayo 2023",
    },
    
    {

      id: 4,
      name: "jurassic world",
      rating: 4.8,
      time: "2H : 12M",
      desc: "Una nueva especie de dinosaurio, creada por los científicos de forma artificial, es más inteligente y peligrosa que los animales conocidos y termina por atacar a los turistas que visitan el parque temático Jurassic World, situado en una isla frente a Costa Rica. ",
      starring: "Chris pratt, Brice Dallas",
      genres: "Ciencia ficción",
      tags: "Adventures, Accion, Supervivencia",
      cover: "../img/images/upcome/jurasico.png",
      video: "../video/ola.mp4",
      date: "12 Junio 2015",
    },
    {
      id: 5,
      name: "lone survivor",
      rating: 4.9,
      time: "2H : 10M",
      desc: "Durante la guerra en Afganistán, un equipo de élite de las fuerzas especiales SEAL, liderado por Marcus Luttrell, tiene la misión de capturar al líder talibán Ahmad Shah, mientras cada uno trata de pelear por su vida.",
      starring: "Mark Wahlberg, Taylor Kitsch, Emile Hirsch",
      genres: "Action, Bélico",
      tags: "Accion, Basada",
      cover: "../img/images/upcome/uni_sobrev.png",
      video: "../video/lone.mp4",
      date: "10 Junio 2013",
    } 
  ]
  
  export const upcome = [
    {
        id: 1,
        cover: "../img/images/alien.png",
        name: "Alien",
        time: "2h : 25m",
      },
    {
      id: 2,
      cover: "../img/images/depre.png",
      name: "The Predator",
      time: "2h : 02m",
    },
    {
      id: 3,
      cover: "../img/images/siete.png",
      name: "Siete Almas",
      time: "2h : 45m",
    },
    {
      id: 4,
      cover: "../img/images/lagimas.png",
      name: "Lagrimas del sol",
      time: "2h : 10m",
    },
    {
      id: 5,
      cover: "../img/images/kong.png",
      name: "Kong",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../img/images/fury.jpg",
      name: "Fury",
      time: "2h : 05m",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: "../img/images/dinoHo.png",
      name: "Dinosaurio",
      time: "2 Hr : 10 min",
    },
    {
      id: 2,
      cover: "../img/images/super.png",
      name: "Superman",
      time: "2 Hr : 20 Min",
    },
    {
      id: 3,
      cover: "../img/images/chitaRun.png",
      name: "Africa Salvaje",
      time: "2h : 02h",
    },
    {
      id: 4,
      cover: "../img/images/kong.png",
      name: "Kong",
      time: "2h : 25m",
    },
    {
      id: 5,
      cover: "../img/images/alien.png",
      name: "Alien",
      time: "2h : 00m",
    },
  ]
  
  export const loMasVisto = [
    {
      id: 1,
      name: "Africa salvaje",
      rating: 4.8,
      time: "1h : 05m",
      desc: "El guepardo es el animal terrestre más veloz del mundo: corre a una velocidad máxima de entre 95 y 115 km/h (puede alcanzar los 95 km/h en solo tres segundos), El guepardo posee una anatomía especializada para la carrera. Posee el mayor corazón en proporción a su tamaño de todos los felinos, lo que le permite bombear la sangre con más fuerza hacia todo su cuerpo",
      starring: "El Guepardo",
      genres: "Supervivencia",
      tags: "Aventura Supervivencia",
      cover: "../img/images/chitaRun.png",
      date: "14 Mayo 2023",
    },
    {
      id: 2,
      name: "The Dinosaur",
      rating: 4.7,
      time: "2h : 12m",
      desc: "Tyrannosaurus rex es la única especie conocida del género fósil Tyrannosaurus de dinosaurio terópodo tiranosáurido, que vivió a finales del período Cretácico, hace aproximadamente entre 68 y 66 millones de años, el Maastrichtiense, en lo que es hoy América del Norte.",
      starring: "Tiranosaurio rex",
      genres: "Action",
      tags: "Adventures",
      cover: "../img/images/dinoHo.png",
      date: "14 May 2023",
    },
    {
      id: 3,
      name: "Alien",
      rating: 4.6,
      time: "2h : 10m",
      desc: "La nave comercial Nostromo y su tripulación, siete hombres y mujeres, se disponen a volver a la Tierra transportando un cargamento de mineral importante. Pero cuando se detienen forzosamente en un planeta desierto, el oficial Kane es repentinamente atacado por una forma de vida desconocida, un arácnido que se adhiere a su cara. Después de que al doctor se le retire el espécimen con ayuda de todos, la tripulación se queda más tranquila y cenan juntos. Justo entonces, Kane empieza a sufrir arcadas y convulsiones y ve cómo su abdomen es perforado por un cuerpo extraño vivo, que se escapa por el pasillo de la nave. Se encuentran en medio del espacio exterior y en compañía de un alienígena.",
      starring: " Sigourney Weaver Tom Skerritt Veronica Cartwright",
      genres: "Adventures",
      tags: " Ciencia Ficción",
      cover: "../img/images/alien.png",
      date: "06 Junio 1978",
    },
    {
      id: 4,
      name: "Jurassic World",
      rating: 4.8,
      time: "1h : 58m",
      desc: "Un parque temático de dinosaurios busca atraer turistas con una emocionante exhibición, pero su criatura más temible logra escapar y desata el caos en la isla. ",
      starring: "	Chris Pratt, Bryce Dallas Howard, Ty Simpkins",
      genres: "Ciencia ficción",
      tags: "Adventures Action ",
      cover: "../img/images/slide1.png",
      date: "20 Junio 2015",
    },
  ]
  export const recomendado = [
    {
      id: 1,
      cover: "../img/images/kong.png",
      name: "Kong",
      time: "2h : 25m",
    },
    {
      id: 2,
      cover: "../img/images/alien.png",
      name: "Alien",
      time: "2h : 00m",
    },
    {
      id: 3,
      cover: "../img/images/dinoHo.png",
      name: "Dinosaurio",
      time: "2h : 10m",
    },
    {
      id: 4,
      cover: "../img/images/super.png",
      name: "Superman",
      time: "2h : 20m",
    },
    {
      id: 5,
      cover: "../img/images/depre.png",
      name: "The Predator",
      time: "2h : 02m",
    },
    {
      id: 6,
      cover: "../img/images/siete.png",
      name: "Siete Almas",
      time: "2h : 45m",
    },
    {
      id: 7,
      cover: "../img/images/lagimas.png",
      name: "Lagrimas del sol",
      time: "2h : 10m",
    },
  ]
  
  